### ISSUE TITLE
Fit Params disappears

### ISSUE THREAD

**Issue by sofiadonnecke** [brettrhenderson/Catacycle#12]
-store current concentrations, poison and order upon plotting parameters so they can be edited and don't refresh

**Comment by brettrhenderson** [comment]
# Cause
The param-submit callback uses plotSuccess, which removes any existing parameters with the line 
``` python
$( ".concentration-form" ).remove(); 
```

as if a new dataset has been uploaded and is being plotted.

# Solution
Write a new callback specifically for the fitting, `fitSuccess()`. This can be simpler than plotSuccess as it only needs to update the plot and need not do anything with the input forms.
